name: Draw ZMK keymaps
on:
  workflow_dispatch:
  push:
    paths:
      - 'config/*.keymap'
      - 'config/includes/*.dtsi'
      - keymap-drawer/config.yaml
      - .github/workflows/draw-keymaps.yml

permissions:
  contents: write

concurrency:
  group: keymap-drawer
  cancel-in-progress: true

jobs:
  draw:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@e30a2e6ae744fa23b943938f3c8ba7b6c675e38e
    with:
      keymap_patterns: 'config/*.keymap'
      config_path: keymap-drawer/config.yaml
      output_folder: keymap-drawer
      install_branch: v0.20.0
      amend_commit: true
      json_path: keymap-drawer/layouts
      fail_on_error: true
